spring:
    profiles:
        # 默认激活 dev 环境
        active: dev
    jackson:
        # 设置后台对于参数为 null 的值，不返回给前台（看数据情况选择）
        # default-property-inclusion: non_null
    servlet:
        multipart:
            # 限制单个上传文件的最大大小为 10MB。如果上传的文件大小超过这个值，将会被拒绝上传。
            max-file-size: 10MB
            # 限制整个上传请求的最大大小为 10MB。这包括所有上传文件的大小之和。如果请求总大小超过这个值，将会被拒绝。
            max-request-size: 10MB
jwt:
    # 签发人
    issuer: dakkkk
    # 秘钥（使用JwtTokenHelper中的main方法生成）
    secret: GAHkw17oWXMOXsR0MDau5qceWzKIIbSLuY/bgOtrIlalIm0+7c5/HYUGH3SIy50rALrqXPeCfL5RCdCWZlLZYw==
    # token 过期时间（单位：分钟） 24*60
    tokenExpireTime: 1440
    # token 请求头中的 key 值
    tokenHeaderKey: Authorization
    # token 请求头中 value值的前缀
    tokenPrefix: Bearer