spring:
    datasource:
#        driver-class-name: com.mysql.cj.jdbc.Driver
        # 使用 p6spy 的驱动
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        url: jdbc:p6spy:mysql://localhost:3306/dkblog?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
        username: root
        password: abc123
        hikari:
            minimum-idle: 5
            maximum-pool-size: 20
            auto-commit: true
            idle-timeout: 30000
            pool-name: dkblog-HikariCP
            max-lifetime: 1800000
            connection-timeout: 30000
            connection-test-query: SELECT 1
    security:
      user:
          name: admin
          password: 123456
minio:
    endpoint: http://127.0.0.1:9000
    accessKey: dakkk
    secretKey: abc123456
    bucketName: dkblog